name: SRE Log Analyzer CI

on:
  push:
    branches:
      - main
      - feature-github-actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Success Message
        run: echo "SRE Log Analyzer CI Successful"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate Python Script
        run: python -m py_compile analyzer.py

      - name: Generate HTML Report
        run: python analyzer.py
`
